# 기상청 단기예보 , 초단기실황 데이터 (18.01~18.12)
### 강수상태 요소 사용
### 서울특별시에 해당하는 지역 ( 기상청 지점좌표 참조 _ 30개 동네 데이터 사용 )
### https://data.kma.go.kr/cmmn/main.do

## 1) 단기예보

In [737]:
import pandas as pd
import numpy as np
import math
import datetime as dt
from datetime import datetime

### 데이터 불러오기 * 데이터 확인

In [738]:
s_57_125= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_3/423_20200524173445439.csv')
s_57_126= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_3/423_20200524173444375.csv')
s_57_127= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_3/423_20200524173444642.csv')

s_58_124= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_2/423_20200524173503012.csv')
s_58_125= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_3/423_20200524173445107.csv')
s_58_126= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_3/423_20200524173444010.csv')
s_58_127= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_3/423_20200524173443605.csv')

s_59_124= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_2/423_20200524173502229.csv')
s_59_125= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_2/423_20200524173502556.csv')
s_59_126= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_1/423_20200524173403166.csv')
s_59_127= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_3/423_20200524173442858.csv')
s_59_128= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_3/423_20200524173443283.csv')

s_60_125= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_2/423_20200524173503309.csv')
s_60_126= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_1/423_20200524173402841.csv')
s_60_127= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_1/423_20200524173358572.csv')
s_60_128= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_1/423_20200524173404956.csv')

s_61_124= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_2/423_20200524173504060.csv')
s_61_125= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_2/423_20200524173503570.csv')
s_61_126= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_1/423_20200524173403513.csv')
s_61_127= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_1/423_20200524173402265.csv')
s_61_128= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_1/423_20200524173405217.csv')
s_61_129= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_3/423_20200524173442166.csv')

s_62_125= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_2/423_20200524173504436.csv')
s_62_126= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_1/423_20200524173403806.csv')
s_62_127= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_1/423_20200524173404103.csv')
s_62_128= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_1/423_20200524173404584.csv')
s_62_129= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_3/423_20200524173442515.csv')

s_63_125= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_2/423_20200524173504761.csv')
s_63_126= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_2/423_20200524173505052.csv')
s_63_127= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/동네예보_서울_2018_2/423_20200524173505410.csv')

### columns 이름 변경

In [739]:
colnaming = ['date' , 'hour' ,'forecast','value']
s_57_125.columns = colnaming
s_57_126.columns = colnaming
s_57_127.columns = colnaming

s_58_124.columns = colnaming
s_58_125.columns = colnaming
s_58_126.columns = colnaming
s_58_127.columns = colnaming

s_59_124.columns = colnaming
s_59_125.columns = colnaming
s_59_126.columns = colnaming
s_59_127.columns = colnaming
s_59_128.columns = colnaming

s_60_125.columns = colnaming
s_60_126.columns = colnaming
s_60_127.columns = colnaming
s_60_128.columns = colnaming

s_61_124.columns = colnaming
s_61_125.columns = colnaming
s_61_126.columns = colnaming
s_61_127.columns = colnaming
s_61_128.columns = colnaming
s_61_129.columns = colnaming

s_62_125.columns = colnaming
s_62_126.columns = colnaming
s_62_127.columns = colnaming
s_62_128.columns = colnaming
s_62_129.columns = colnaming

s_63_125.columns = colnaming
s_63_126.columns = colnaming
s_63_127.columns = colnaming

### Datetime 패키지 이용을 위해, 날짜 정보 numeric화

In [740]:
s_57_125['date'] = pd.to_numeric(s_57_125['date'] , errors='coerce')
s_57_126['date'] = pd.to_numeric(s_57_126['date'] , errors='coerce')
s_57_127['date'] = pd.to_numeric(s_57_127['date'] , errors='coerce')

s_58_124['date'] = pd.to_numeric(s_58_124['date'] , errors='coerce')
s_58_125['date'] = pd.to_numeric(s_58_125['date'] , errors='coerce')
s_58_126['date'] = pd.to_numeric(s_58_126['date'] , errors='coerce')
s_58_127['date'] = pd.to_numeric(s_58_127['date'] , errors='coerce')

s_59_124['date'] = pd.to_numeric(s_59_124['date'] , errors='coerce')
s_59_125['date'] = pd.to_numeric(s_59_125['date'] , errors='coerce')
s_59_126['date'] = pd.to_numeric(s_59_126['date'] , errors='coerce')
s_59_127['date'] = pd.to_numeric(s_59_127['date'] , errors='coerce')
s_59_128['date'] = pd.to_numeric(s_59_128['date'] , errors='coerce')

s_60_125['date'] = pd.to_numeric(s_60_125['date'] , errors='coerce')
s_60_126['date'] = pd.to_numeric(s_60_126['date'] , errors='coerce')
s_60_127['date'] = pd.to_numeric(s_60_127['date'] , errors='coerce')
s_60_128['date'] = pd.to_numeric(s_60_128['date'] , errors='coerce')

s_61_124['date'] = pd.to_numeric(s_61_124['date'] , errors='coerce')
s_61_125['date'] = pd.to_numeric(s_61_125['date'] , errors='coerce')
s_61_126['date'] = pd.to_numeric(s_61_126['date'] , errors='coerce')
s_61_127['date'] = pd.to_numeric(s_61_127['date'] , errors='coerce')
s_61_128['date'] = pd.to_numeric(s_61_128['date'] , errors='coerce')
s_61_129['date'] = pd.to_numeric(s_61_129['date'] , errors='coerce')

s_62_125['date'] = pd.to_numeric(s_62_125['date'] , errors='coerce')
s_62_126['date'] = pd.to_numeric(s_62_126['date'] , errors='coerce')
s_62_127['date'] = pd.to_numeric(s_62_127['date'] , errors='coerce')
s_62_128['date'] = pd.to_numeric(s_62_128['date'] , errors='coerce')
s_62_129['date'] = pd.to_numeric(s_62_129['date'] , errors='coerce')

s_63_125['date'] = pd.to_numeric(s_63_125['date'] , errors='coerce')
s_63_126['date'] = pd.to_numeric(s_63_126['date'] , errors='coerce')
s_63_127['date'] = pd.to_numeric(s_63_127['date'] , errors='coerce')

In [741]:
s_57_125['hour'] = pd.to_numeric(s_57_125['hour'] , errors='coerce')
s_57_126['hour'] = pd.to_numeric(s_57_126['hour'] , errors='coerce')
s_57_127['hour'] = pd.to_numeric(s_57_127['hour'] , errors='coerce')

s_58_124['hour'] = pd.to_numeric(s_58_124['hour'] , errors='coerce')
s_58_125['hour'] = pd.to_numeric(s_58_125['hour'] , errors='coerce')
s_58_126['hour'] = pd.to_numeric(s_58_126['hour'] , errors='coerce')
s_58_127['hour'] = pd.to_numeric(s_58_127['hour'] , errors='coerce')

s_59_124['hour'] = pd.to_numeric(s_59_124['hour'] , errors='coerce')
s_59_125['hour'] = pd.to_numeric(s_59_125['hour'] , errors='coerce')
s_59_126['hour'] = pd.to_numeric(s_59_126['hour'] , errors='coerce')
s_59_127['hour'] = pd.to_numeric(s_59_127['hour'] , errors='coerce')
s_59_128['hour'] = pd.to_numeric(s_59_128['hour'] , errors='coerce')

s_60_125['hour'] = pd.to_numeric(s_60_125['hour'] , errors='coerce')
s_60_126['hour'] = pd.to_numeric(s_60_126['hour'] , errors='coerce')
s_60_127['hour'] = pd.to_numeric(s_60_127['hour'] , errors='coerce')
s_60_128['hour'] = pd.to_numeric(s_60_128['hour'] , errors='coerce')

s_61_124['hour'] = pd.to_numeric(s_61_124['hour'] , errors='coerce')
s_61_125['hour'] = pd.to_numeric(s_61_125['hour'] , errors='coerce')
s_61_126['hour'] = pd.to_numeric(s_61_126['hour'] , errors='coerce')
s_61_127['hour'] = pd.to_numeric(s_61_127['hour'] , errors='coerce')
s_61_128['hour'] = pd.to_numeric(s_61_128['hour'] , errors='coerce')
s_61_129['hour'] = pd.to_numeric(s_61_129['hour'] , errors='coerce')

s_62_125['hour'] = pd.to_numeric(s_62_125['hour'] , errors='coerce')
s_62_126['hour'] = pd.to_numeric(s_62_126['hour'] , errors='coerce')
s_62_127['hour'] = pd.to_numeric(s_62_127['hour'] , errors='coerce')
s_62_128['hour'] = pd.to_numeric(s_62_128['hour'] , errors='coerce')
s_62_129['hour'] = pd.to_numeric(s_62_129['hour'] , errors='coerce')

s_63_125['hour'] = pd.to_numeric(s_63_125['hour'] , errors='coerce')
s_63_126['hour'] = pd.to_numeric(s_63_126['hour'] , errors='coerce')
s_63_127['hour'] = pd.to_numeric(s_63_127['hour'] , errors='coerce')

In [742]:
s_57_125['forecast'] = pd.to_numeric(s_57_125['forecast'] , errors='coerce')
s_57_126['forecast'] = pd.to_numeric(s_57_126['forecast'] , errors='coerce')
s_57_127['forecast'] = pd.to_numeric(s_57_127['forecast'] , errors='coerce')

s_58_124['forecast'] = pd.to_numeric(s_58_124['forecast'] , errors='coerce')
s_58_125['forecast'] = pd.to_numeric(s_58_125['forecast'] , errors='coerce')
s_58_126['forecast'] = pd.to_numeric(s_58_126['forecast'] , errors='coerce')
s_58_127['forecast'] = pd.to_numeric(s_58_127['forecast'] , errors='coerce')

s_59_124['forecast'] = pd.to_numeric(s_59_124['forecast'] , errors='coerce')
s_59_125['forecast'] = pd.to_numeric(s_59_125['forecast'] , errors='coerce')
s_59_126['forecast'] = pd.to_numeric(s_59_126['forecast'] , errors='coerce')
s_59_127['forecast'] = pd.to_numeric(s_59_127['forecast'] , errors='coerce')
s_59_128['forecast'] = pd.to_numeric(s_59_128['forecast'] , errors='coerce')

s_60_125['forecast'] = pd.to_numeric(s_60_125['forecast'] , errors='coerce')
s_60_126['forecast'] = pd.to_numeric(s_60_126['forecast'] , errors='coerce')
s_60_127['forecast'] = pd.to_numeric(s_60_127['forecast'] , errors='coerce')
s_60_128['forecast'] = pd.to_numeric(s_60_128['forecast'] , errors='coerce')

s_61_124['forecast'] = pd.to_numeric(s_61_124['forecast'] , errors='coerce')
s_61_125['forecast'] = pd.to_numeric(s_61_125['forecast'] , errors='coerce')
s_61_126['forecast'] = pd.to_numeric(s_61_126['forecast'] , errors='coerce')
s_61_127['forecast'] = pd.to_numeric(s_61_127['forecast'] , errors='coerce')
s_61_128['forecast'] = pd.to_numeric(s_61_128['forecast'] , errors='coerce')
s_61_129['forecast'] = pd.to_numeric(s_61_129['forecast'] , errors='coerce')

s_62_125['forecast'] = pd.to_numeric(s_62_125['forecast'] , errors='coerce')
s_62_126['forecast'] = pd.to_numeric(s_62_126['forecast'] , errors='coerce')
s_62_127['forecast'] = pd.to_numeric(s_62_127['forecast'] , errors='coerce')
s_62_128['forecast'] = pd.to_numeric(s_62_128['forecast'] , errors='coerce')
s_62_129['forecast'] = pd.to_numeric(s_62_129['forecast'] , errors='coerce')

s_63_125['forecast'] = pd.to_numeric(s_63_125['forecast'] , errors='coerce')
s_63_126['forecast'] = pd.to_numeric(s_63_126['forecast'] , errors='coerce')
s_63_127['forecast'] = pd.to_numeric(s_63_127['forecast'] , errors='coerce')

### Datetime 패키지 사용위한 연산

[4588,8733, 13322 , 17763 , 22352 , 26793 , 31382 , 35971 , 40412 , 45001 , 49442] : csv 파일 내, 월 구분되는 행 번호

In [743]:
s_57_125['new_date'] = pd.concat([s_57_125['date'].iloc[0:4588,] + 20180100 , s_57_125['date'].iloc[4589:8733,] + 20180200 ,
                                     s_57_125['date'].iloc[8734:13322,] + 20180300, s_57_125['date'].iloc[13323:17763,] + 20180400,
                                     s_57_125['date'].iloc[17764:22352,] + 20180500 , s_57_125['date'].iloc[22353:26793,] + 20180600,
                                     s_57_125['date'].iloc[26794:31382,] + 20180700 , s_57_125['date'].iloc[31383:35971,] + 20180800,
                                     s_57_125['date'].iloc[35972:40412,] + 20180900 , s_57_125['date'].iloc[40413:45001,] + 20181000,
                                     s_57_125['date'].iloc[45002:49442,] + 20181100 , s_57_125['date'].iloc[49443:54031,] + 20181200])

In [744]:
s_57_125['new_date'] = s_57_125['new_date']*10000

In [745]:
s_57_125['new_date'] =s_57_125['new_date'] +s_57_125['hour']

In [746]:
s_57_125['new_date'] = pd.to_datetime(s_57_125['new_date'], format='%Y%m%d%H%M')

In [747]:
s_57_125['new_date']= s_57_125['new_date']
s_57_126['new_date']= s_57_125['new_date']
s_57_127['new_date']= s_57_125['new_date']
s_58_124['new_date']= s_57_125['new_date']
s_58_125['new_date']= s_57_125['new_date']
s_58_126['new_date']= s_57_125['new_date']
s_58_127['new_date']= s_57_125['new_date']
s_59_124['new_date']= s_57_125['new_date']
s_59_125['new_date']= s_57_125['new_date']
s_59_126['new_date']= s_57_125['new_date']
s_59_127['new_date']= s_57_125['new_date']
s_59_128['new_date']= s_57_125['new_date']
s_60_125['new_date']= s_57_125['new_date']
s_60_126['new_date']= s_57_125['new_date']
s_60_127['new_date']= s_57_125['new_date']
s_60_128['new_date']= s_57_125['new_date']
s_61_124['new_date']= s_57_125['new_date']
s_61_125['new_date']= s_57_125['new_date']
s_61_126['new_date']= s_57_125['new_date']
s_61_127['new_date']= s_57_125['new_date']
s_61_128['new_date']= s_57_125['new_date']
s_61_129['new_date']= s_57_125['new_date']
s_62_125['new_date']= s_57_125['new_date']
s_62_126['new_date']= s_57_125['new_date']
s_62_127['new_date']= s_57_125['new_date']
s_62_128['new_date']= s_57_125['new_date']
s_62_129['new_date']= s_57_125['new_date']
s_63_125['new_date']= s_57_125['new_date']
s_63_126['new_date']= s_57_125['new_date']
s_63_127['new_date']= s_57_125['new_date']

### Datetime 패키지에 사용가능한 달짜 데이터, index로 설정

In [748]:
s_57_125.set_index(s_57_125['new_date'],inplace=True ,drop=True)
s_57_126.set_index(s_57_126['new_date'],inplace=True ,drop=True)
s_57_127.set_index(s_57_127['new_date'],inplace=True ,drop=True)

s_58_124.set_index(s_58_124['new_date'],inplace=True ,drop=True)
s_58_125.set_index(s_58_125['new_date'],inplace=True ,drop=True)
s_58_126.set_index(s_58_126['new_date'],inplace=True ,drop=True)
s_58_127.set_index(s_58_127['new_date'],inplace=True ,drop=True)

s_59_124.set_index(s_59_124['new_date'],inplace=True ,drop=True)
s_59_125.set_index(s_59_125['new_date'],inplace=True ,drop=True)
s_59_126.set_index(s_59_126['new_date'],inplace=True ,drop=True)
s_59_127.set_index(s_59_127['new_date'],inplace=True ,drop=True)
s_59_128.set_index(s_59_128['new_date'],inplace=True ,drop=True)

s_60_125.set_index(s_60_125['new_date'],inplace=True ,drop=True)
s_60_126.set_index(s_60_126['new_date'],inplace=True ,drop=True)
s_60_127.set_index(s_60_127['new_date'],inplace=True ,drop=True)
s_60_128.set_index(s_60_128['new_date'],inplace=True ,drop=True)

s_61_124.set_index(s_61_124['new_date'],inplace=True ,drop=True)
s_61_125.set_index(s_61_125['new_date'],inplace=True ,drop=True)
s_61_126.set_index(s_61_126['new_date'],inplace=True ,drop=True)
s_61_127.set_index(s_61_127['new_date'],inplace=True ,drop=True)
s_61_128.set_index(s_61_128['new_date'],inplace=True ,drop=True)
s_61_129.set_index(s_61_129['new_date'],inplace=True ,drop=True)

s_62_125.set_index(s_62_125['new_date'],inplace=True ,drop=True)
s_62_126.set_index(s_62_126['new_date'],inplace=True ,drop=True)
s_62_127.set_index(s_62_127['new_date'],inplace=True ,drop=True)
s_62_128.set_index(s_62_128['new_date'],inplace=True ,drop=True)
s_62_129.set_index(s_62_129['new_date'],inplace=True ,drop=True)

s_63_125.set_index(s_63_125['new_date'],inplace=True ,drop=True)
s_63_126.set_index(s_63_126['new_date'],inplace=True ,drop=True)
s_63_127.set_index(s_63_127['new_date'],inplace=True ,drop=True)

### 각 지역에 해당하는 예측값들 각 지역 좌표로 표현한 columns name 으로 변경

In [749]:
s_57_125.rename(columns = {'value' : 's_57_125'},inplace=True)
s_57_126.rename(columns = {'value' : 's_57_126'},inplace=True)
s_57_127.rename(columns = {'value' : 's_57_127'},inplace=True)

s_58_124.rename(columns = {'value' : 's_58_124'},inplace=True)
s_58_125.rename(columns = {'value' : 's_58_125'},inplace=True)
s_58_126.rename(columns = {'value' : 's_58_126'},inplace=True)
s_58_127.rename(columns = {'value' : 's_58_127'},inplace=True)

s_59_124.rename(columns = {'value' : 's_59_124'},inplace=True)
s_59_125.rename(columns = {'value' : 's_59_125'},inplace=True)
s_59_126.rename(columns = {'value' : 's_59_126'},inplace=True)
s_59_127.rename(columns = {'value' : 's_59_127'},inplace=True)
s_59_128.rename(columns = {'value' : 's_59_128'},inplace=True)

s_60_125.rename(columns = {'value' : 's_60_125'},inplace=True)
s_60_126.rename(columns = {'value' : 's_60_126'},inplace=True)
s_60_127.rename(columns = {'value' : 's_60_127'},inplace=True)
s_60_128.rename(columns = {'value' : 's_60_128'},inplace=True)

s_61_124.rename(columns = {'value' : 's_61_124'},inplace=True)
s_61_125.rename(columns = {'value' : 's_61_125'},inplace=True)
s_61_126.rename(columns = {'value' : 's_61_126'},inplace=True)
s_61_127.rename(columns = {'value' : 's_61_127'},inplace=True)
s_61_128.rename(columns = {'value' : 's_61_128'},inplace=True)
s_61_129.rename(columns = {'value' : 's_61_129'},inplace=True)

s_62_125.rename(columns = {'value' : 's_62_125'},inplace=True)
s_62_126.rename(columns = {'value' : 's_62_126'},inplace=True)
s_62_127.rename(columns = {'value' : 's_62_127'},inplace=True)
s_62_128.rename(columns = {'value' : 's_62_128'},inplace=True)
s_62_129.rename(columns = {'value' : 's_62_129'},inplace=True)

s_63_125.rename(columns = {'value' : 's_63_125'},inplace=True)
s_63_126.rename(columns = {'value' : 's_63_126'},inplace=True)
s_63_127.rename(columns = {'value' : 's_63_127'},inplace=True)

### 필요없는 colmuns 제거 , forecast 변수는 동일한 변수값을 가지기 때문에 1개의 변수만 사용

In [751]:
s_57_125.drop(['date','hour','new_date'],axis=1,inplace=True)
s_57_126.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_57_127.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)

s_58_124.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_58_125.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_58_126.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_58_127.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)

s_59_124.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_59_125.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_59_126.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_59_127.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_59_128.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)

s_60_125.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_60_126.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_60_127.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_60_128.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)

s_61_124.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_61_125.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_61_126.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_61_127.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_61_128.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_61_129.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)

s_62_125.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_62_126.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_62_127.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_62_128.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_62_129.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)

s_63_125.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_63_126.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)
s_63_127.drop(['date','hour','new_date','forecast'],axis=1,inplace=True)

### 하나의 데이터프레임으로 결합

In [752]:
s_forecast = pd.concat([s_57_125,
s_57_126,
s_57_127,

s_58_124,
s_58_125,
s_58_126,
s_58_127,

s_59_124,
s_59_125,
s_59_126,
s_59_127,
s_59_128,

s_60_125,
s_60_126,
s_60_127,
s_60_128,

s_61_124,
s_61_125,
s_61_126,
s_61_127,
s_61_128,
s_61_129,

s_62_125,
s_62_126,
s_62_127,
s_62_128,
s_62_129,

s_63_125,
s_63_126,
s_63_127,
],axis=1)

In [753]:
s_forecast

,forecast,s_57_125,s_57_126,s_57_127,s_58_124,s_58_125,s_58_126,s_58_127,s_59_124,s_59_125,...,s_61_128,s_61_129,s_62_125,s_62_126,s_62_127,s_62_128,s_62_129,s_63_125,s_63_126,s_63_127
new_date,,,,,,,,,,,,,,,,,,,,,
2018-01-01 02:00:00,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2018-01-01 02:00:00,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2018-01-01 02:00:00,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2018-01-01 02:00:00,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2018-01-01 02:00:00,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-31 23:00:00,52.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2018-12-31 23:00:00,55.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2018-12-31 23:00:00,58.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2018-12-31 23:00:00,61.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2018-12-31 23:00:00,64.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### csv파일 내, 월 구분하는 행이 존재하므로 각 열에서 11개의 NA값 존재 , 해당 NA값 제거

In [755]:
s_forecast.isnull().sum()

forecast    11
s_57_125    11
s_57_126    11
s_57_127    11
s_58_124    11
s_58_125    11
s_58_126    11
s_58_127    11
s_59_124    11
s_59_125    11
s_59_126    11
s_59_127    11
s_59_128    11
s_60_125    11
s_60_126    11
s_60_127    11
s_60_128    11
s_61_124    11
s_61_125    11
s_61_126    11
s_61_127    11
s_61_128    11
s_61_129    11
s_62_125    11
s_62_126    11
s_62_127    11
s_62_128    11
s_62_129    11
s_63_125    11
s_63_126    11
s_63_127    11
dtype: int64

In [756]:
s_forecast.dropna(inplace=True)

### 예측값의 코드값 (2 :비_눈 , 3 :눈 , 4:소나기) 모두' 비' (1) 코드값으로 변경

In [762]:
for num in s_forecast.columns[1:]:
    s_forecast[num] = s_forecast[num].apply(lambda x:1 if x == 2 else x)
for num in s_forecast.columns[1:]:
    s_forecast[num] = s_forecast[num].apply(lambda x:1 if x == 3 else x)
for num in s_forecast.columns[1:]:
    s_forecast[num] = s_forecast[num].apply(lambda x:1 if x == 4 else x)

In [768]:
s_forecast.to_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/s_forecast.csv')

## 2) 초단기 실황

### 데이터 불러오기 * 데이터 확인

In [771]:
s_57_125= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_2/400_20200524182420134.csv')
s_57_126= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_2/400_20200524182419354.csv')
s_57_127= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_2/400_20200524182419539.csv')

s_58_124= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_3/400_20200524182427758.csv')
s_58_125= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_2/400_20200524182419938.csv')
s_58_126= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_2/400_20200524182419139.csv')
s_58_127= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_2/400_20200524182418939.csv')

s_59_124= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_3/400_20200524182427185.csv')
s_59_125= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_3/400_20200524182427518.csv')
s_59_126= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_1/400_20200524182406798.csv')
s_59_127= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_2/400_20200524182418486.csv')
s_59_128= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_2/400_20200524182418768.csv')

s_60_125= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_3/400_20200524182427994.csv')
s_60_126= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_1/400_20200524182406582.csv')
s_60_127= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_1/400_20200524182402481.csv')
s_60_128= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_1/400_20200524182407854.csv')

s_61_124= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_3/400_20200524182428434.csv')
s_61_125= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_3/400_20200524182428194.csv')
s_61_126= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_1/400_20200524182406998.csv')
s_61_127= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_1/400_20200524182406154.csv')
s_61_128= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_1/400_20200524182408017.csv')
s_61_129= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_2/400_20200524182418063.csv')

s_62_125= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_3/400_20200524182428628.csv')
s_62_126= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_1/400_20200524182407188.csv')
s_62_127= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_1/400_20200524182407380.csv')
s_62_128= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_1/400_20200524182407680.csv')
s_62_129= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_2/400_20200524182418257.csv')

s_63_125= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_3/400_20200524182428874.csv')
s_63_126= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_3/400_20200524182429080.csv')
s_63_127= pd.read_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/실황_서울_2018_3/400_20200524182429309.csv')

### columns 이름 변경

In [773]:
colnaming = ['date' , 'hour' ,'value']
s_57_125.columns = colnaming
s_57_126.columns = colnaming
s_57_127.columns = colnaming

s_58_124.columns = colnaming
s_58_125.columns = colnaming
s_58_126.columns = colnaming
s_58_127.columns = colnaming

s_59_124.columns = colnaming
s_59_125.columns = colnaming
s_59_126.columns = colnaming
s_59_127.columns = colnaming
s_59_128.columns = colnaming

s_60_125.columns = colnaming
s_60_126.columns = colnaming
s_60_127.columns = colnaming
s_60_128.columns = colnaming

s_61_124.columns = colnaming
s_61_125.columns = colnaming
s_61_126.columns = colnaming
s_61_127.columns = colnaming
s_61_128.columns = colnaming
s_61_129.columns = colnaming

s_62_125.columns = colnaming
s_62_126.columns = colnaming
s_62_127.columns = colnaming
s_62_128.columns = colnaming
s_62_129.columns = colnaming

s_63_125.columns = colnaming
s_63_126.columns = colnaming
s_63_127.columns = colnaming

### Datetime 패키지 이용을 위해, 날짜 정보 numeric화

In [774]:
s_57_125['date'] = pd.to_numeric(s_57_125['date'] , errors='coerce')
s_57_126['date'] = pd.to_numeric(s_57_126['date'] , errors='coerce')
s_57_127['date'] = pd.to_numeric(s_57_127['date'] , errors='coerce')

s_58_124['date'] = pd.to_numeric(s_58_124['date'] , errors='coerce')
s_58_125['date'] = pd.to_numeric(s_58_125['date'] , errors='coerce')
s_58_126['date'] = pd.to_numeric(s_58_126['date'] , errors='coerce')
s_58_127['date'] = pd.to_numeric(s_58_127['date'] , errors='coerce')

s_59_124['date'] = pd.to_numeric(s_59_124['date'] , errors='coerce')
s_59_125['date'] = pd.to_numeric(s_59_125['date'] , errors='coerce')
s_59_126['date'] = pd.to_numeric(s_59_126['date'] , errors='coerce')
s_59_127['date'] = pd.to_numeric(s_59_127['date'] , errors='coerce')
s_59_128['date'] = pd.to_numeric(s_59_128['date'] , errors='coerce')

s_60_125['date'] = pd.to_numeric(s_60_125['date'] , errors='coerce')
s_60_126['date'] = pd.to_numeric(s_60_126['date'] , errors='coerce')
s_60_127['date'] = pd.to_numeric(s_60_127['date'] , errors='coerce')
s_60_128['date'] = pd.to_numeric(s_60_128['date'] , errors='coerce')

s_61_124['date'] = pd.to_numeric(s_61_124['date'] , errors='coerce')
s_61_125['date'] = pd.to_numeric(s_61_125['date'] , errors='coerce')
s_61_126['date'] = pd.to_numeric(s_61_126['date'] , errors='coerce')
s_61_127['date'] = pd.to_numeric(s_61_127['date'] , errors='coerce')
s_61_128['date'] = pd.to_numeric(s_61_128['date'] , errors='coerce')
s_61_129['date'] = pd.to_numeric(s_61_129['date'] , errors='coerce')

s_62_125['date'] = pd.to_numeric(s_62_125['date'] , errors='coerce')
s_62_126['date'] = pd.to_numeric(s_62_126['date'] , errors='coerce')
s_62_127['date'] = pd.to_numeric(s_62_127['date'] , errors='coerce')
s_62_128['date'] = pd.to_numeric(s_62_128['date'] , errors='coerce')
s_62_129['date'] = pd.to_numeric(s_62_129['date'] , errors='coerce')

s_63_125['date'] = pd.to_numeric(s_63_125['date'] , errors='coerce')
s_63_126['date'] = pd.to_numeric(s_63_126['date'] , errors='coerce')
s_63_127['date'] = pd.to_numeric(s_63_127['date'] , errors='coerce')

In [775]:
s_57_125['hour'] = pd.to_numeric(s_57_125['hour'] , errors='coerce')
s_57_126['hour'] = pd.to_numeric(s_57_126['hour'] , errors='coerce')
s_57_127['hour'] = pd.to_numeric(s_57_127['hour'] , errors='coerce')

s_58_124['hour'] = pd.to_numeric(s_58_124['hour'] , errors='coerce')
s_58_125['hour'] = pd.to_numeric(s_58_125['hour'] , errors='coerce')
s_58_126['hour'] = pd.to_numeric(s_58_126['hour'] , errors='coerce')
s_58_127['hour'] = pd.to_numeric(s_58_127['hour'] , errors='coerce')

s_59_124['hour'] = pd.to_numeric(s_59_124['hour'] , errors='coerce')
s_59_125['hour'] = pd.to_numeric(s_59_125['hour'] , errors='coerce')
s_59_126['hour'] = pd.to_numeric(s_59_126['hour'] , errors='coerce')
s_59_127['hour'] = pd.to_numeric(s_59_127['hour'] , errors='coerce')
s_59_128['hour'] = pd.to_numeric(s_59_128['hour'] , errors='coerce')

s_60_125['hour'] = pd.to_numeric(s_60_125['hour'] , errors='coerce')
s_60_126['hour'] = pd.to_numeric(s_60_126['hour'] , errors='coerce')
s_60_127['hour'] = pd.to_numeric(s_60_127['hour'] , errors='coerce')
s_60_128['hour'] = pd.to_numeric(s_60_128['hour'] , errors='coerce')

s_61_124['hour'] = pd.to_numeric(s_61_124['hour'] , errors='coerce')
s_61_125['hour'] = pd.to_numeric(s_61_125['hour'] , errors='coerce')
s_61_126['hour'] = pd.to_numeric(s_61_126['hour'] , errors='coerce')
s_61_127['hour'] = pd.to_numeric(s_61_127['hour'] , errors='coerce')
s_61_128['hour'] = pd.to_numeric(s_61_128['hour'] , errors='coerce')
s_61_129['hour'] = pd.to_numeric(s_61_129['hour'] , errors='coerce')

s_62_125['hour'] = pd.to_numeric(s_62_125['hour'] , errors='coerce')
s_62_126['hour'] = pd.to_numeric(s_62_126['hour'] , errors='coerce')
s_62_127['hour'] = pd.to_numeric(s_62_127['hour'] , errors='coerce')
s_62_128['hour'] = pd.to_numeric(s_62_128['hour'] , errors='coerce')
s_62_129['hour'] = pd.to_numeric(s_62_129['hour'] , errors='coerce')

s_63_125['hour'] = pd.to_numeric(s_63_125['hour'] , errors='coerce')
s_63_126['hour'] = pd.to_numeric(s_63_126['hour'] , errors='coerce')
s_63_127['hour'] = pd.to_numeric(s_63_127['hour'] , errors='coerce')

### Datetime 패키지 사용위한 연산

744,1417,2162,2883,3628,4349,5094,5839,6560,7305,8026 : csv 파일 내, 월 구분되는 행 번호

In [776]:
s_57_125['new_date'] = pd.concat([s_57_125['date'].iloc[0:744,] + 20180100 , s_57_125['date'].iloc[745:1417,] + 20180200 ,
                                     s_57_125['date'].iloc[1418:2162,] + 20180300 , s_57_125['date'].iloc[2163:2883,] + 20180400,
                                     s_57_125['date'].iloc[2884:3628,] + 20180500 , s_57_125['date'].iloc[3629:4349,] + 20180600,
                                     s_57_125['date'].iloc[4350:5094,] + 20180700 , s_57_125['date'].iloc[5095:5839,] + 20180800,
                                     s_57_125['date'].iloc[5840:6560,] + 20180900 , s_57_125['date'].iloc[6561:7305,] + 20181000,
                                     s_57_125['date'].iloc[7306:8026,] + 20181100 , s_57_125['date'].iloc[8027:8771,] + 20181200])

In [777]:
s_57_125['new_date'] = s_57_125['new_date']*10000

In [778]:
s_57_125['new_date'] =s_57_125['new_date'] +s_57_125['hour']

In [779]:
s_57_125['new_date'] = pd.to_datetime(s_57_125['new_date'], format='%Y%m%d%H%M')

In [ ]:
s_57_125['new_date']= s_57_125['new_date']
s_57_126['new_date']= s_57_125['new_date']
s_57_127['new_date']= s_57_125['new_date']
s_58_124['new_date']= s_57_125['new_date']
s_58_125['new_date']= s_57_125['new_date']
s_58_126['new_date']= s_57_125['new_date']
s_58_127['new_date']= s_57_125['new_date']
s_59_124['new_date']= s_57_125['new_date']
s_59_125['new_date']= s_57_125['new_date']
s_59_126['new_date']= s_57_125['new_date']
s_59_127['new_date']= s_57_125['new_date']
s_59_128['new_date']= s_57_125['new_date']
s_60_125['new_date']= s_57_125['new_date']
s_60_126['new_date']= s_57_125['new_date']
s_60_127['new_date']= s_57_125['new_date']
s_60_128['new_date']= s_57_125['new_date']
s_61_124['new_date']= s_57_125['new_date']
s_61_125['new_date']= s_57_125['new_date']
s_61_126['new_date']= s_57_125['new_date']
s_61_127['new_date']= s_57_125['new_date']
s_61_128['new_date']= s_57_125['new_date']
s_61_129['new_date']= s_57_125['new_date']
s_62_125['new_date']= s_57_125['new_date']
s_62_126['new_date']= s_57_125['new_date']
s_62_127['new_date']= s_57_125['new_date']
s_62_128['new_date']= s_57_125['new_date']
s_62_129['new_date']= s_57_125['new_date']
s_63_125['new_date']= s_57_125['new_date']
s_63_126['new_date']= s_57_125['new_date']
s_63_127['new_date']= s_57_125['new_date']

### 각 지역에 해당하는 예측값들 각 지역 좌표로 표현한 columns name 으로 변경

In [782]:
s_57_125.rename(columns = {'value' : 's_57_125'},inplace=True)
s_57_126.rename(columns = {'value' : 's_57_126'},inplace=True)
s_57_127.rename(columns = {'value' : 's_57_127'},inplace=True)

s_58_124.rename(columns = {'value' : 's_58_124'},inplace=True)
s_58_125.rename(columns = {'value' : 's_58_125'},inplace=True)
s_58_126.rename(columns = {'value' : 's_58_126'},inplace=True)
s_58_127.rename(columns = {'value' : 's_58_127'},inplace=True)

s_59_124.rename(columns = {'value' : 's_59_124'},inplace=True)
s_59_125.rename(columns = {'value' : 's_59_125'},inplace=True)
s_59_126.rename(columns = {'value' : 's_59_126'},inplace=True)
s_59_127.rename(columns = {'value' : 's_59_127'},inplace=True)
s_59_128.rename(columns = {'value' : 's_59_128'},inplace=True)

s_60_125.rename(columns = {'value' : 's_60_125'},inplace=True)
s_60_126.rename(columns = {'value' : 's_60_126'},inplace=True)
s_60_127.rename(columns = {'value' : 's_60_127'},inplace=True)
s_60_128.rename(columns = {'value' : 's_60_128'},inplace=True)

s_61_124.rename(columns = {'value' : 's_61_124'},inplace=True)
s_61_125.rename(columns = {'value' : 's_61_125'},inplace=True)
s_61_126.rename(columns = {'value' : 's_61_126'},inplace=True)
s_61_127.rename(columns = {'value' : 's_61_127'},inplace=True)
s_61_128.rename(columns = {'value' : 's_61_128'},inplace=True)
s_61_129.rename(columns = {'value' : 's_61_129'},inplace=True)

s_62_125.rename(columns = {'value' : 's_62_125'},inplace=True)
s_62_126.rename(columns = {'value' : 's_62_126'},inplace=True)
s_62_127.rename(columns = {'value' : 's_62_127'},inplace=True)
s_62_128.rename(columns = {'value' : 's_62_128'},inplace=True)
s_62_129.rename(columns = {'value' : 's_62_129'},inplace=True)

s_63_125.rename(columns = {'value' : 's_63_125'},inplace=True)
s_63_126.rename(columns = {'value' : 's_63_126'},inplace=True)
s_63_127.rename(columns = {'value' : 's_63_127'},inplace=True)

### Datetime 패키지에 사용가능한 달짜 데이터, index로 설정

In [783]:
s_57_125.set_index(s_57_125['new_date'],inplace=True ,drop=True)
s_57_126.set_index(s_57_126['new_date'],inplace=True ,drop=True)
s_57_127.set_index(s_57_127['new_date'],inplace=True ,drop=True)

s_58_124.set_index(s_58_124['new_date'],inplace=True ,drop=True)
s_58_125.set_index(s_58_125['new_date'],inplace=True ,drop=True)
s_58_126.set_index(s_58_126['new_date'],inplace=True ,drop=True)
s_58_127.set_index(s_58_127['new_date'],inplace=True ,drop=True)

s_59_124.set_index(s_59_124['new_date'],inplace=True ,drop=True)
s_59_125.set_index(s_59_125['new_date'],inplace=True ,drop=True)
s_59_126.set_index(s_59_126['new_date'],inplace=True ,drop=True)
s_59_127.set_index(s_59_127['new_date'],inplace=True ,drop=True)
s_59_128.set_index(s_59_128['new_date'],inplace=True ,drop=True)

s_60_125.set_index(s_60_125['new_date'],inplace=True ,drop=True)
s_60_126.set_index(s_60_126['new_date'],inplace=True ,drop=True)
s_60_127.set_index(s_60_127['new_date'],inplace=True ,drop=True)
s_60_128.set_index(s_60_128['new_date'],inplace=True ,drop=True)

s_61_124.set_index(s_61_124['new_date'],inplace=True ,drop=True)
s_61_125.set_index(s_61_125['new_date'],inplace=True ,drop=True)
s_61_126.set_index(s_61_126['new_date'],inplace=True ,drop=True)
s_61_127.set_index(s_61_127['new_date'],inplace=True ,drop=True)
s_61_128.set_index(s_61_128['new_date'],inplace=True ,drop=True)
s_61_129.set_index(s_61_129['new_date'],inplace=True ,drop=True)

s_62_125.set_index(s_62_125['new_date'],inplace=True ,drop=True)
s_62_126.set_index(s_62_126['new_date'],inplace=True ,drop=True)
s_62_127.set_index(s_62_127['new_date'],inplace=True ,drop=True)
s_62_128.set_index(s_62_128['new_date'],inplace=True ,drop=True)
s_62_129.set_index(s_62_129['new_date'],inplace=True ,drop=True)

s_63_125.set_index(s_63_125['new_date'],inplace=True ,drop=True)
s_63_126.set_index(s_63_126['new_date'],inplace=True ,drop=True)
s_63_127.set_index(s_63_127['new_date'],inplace=True ,drop=True)

### 필요없는 colmuns 제거

In [784]:
s_57_125.drop(['date','hour','new_date'],axis=1,inplace=True)
s_57_126.drop(['date','hour','new_date'],axis=1,inplace=True)
s_57_127.drop(['date','hour','new_date'],axis=1,inplace=True)

s_58_124.drop(['date','hour','new_date'],axis=1,inplace=True)
s_58_125.drop(['date','hour','new_date'],axis=1,inplace=True)
s_58_126.drop(['date','hour','new_date'],axis=1,inplace=True)
s_58_127.drop(['date','hour','new_date'],axis=1,inplace=True)

s_59_124.drop(['date','hour','new_date'],axis=1,inplace=True)
s_59_125.drop(['date','hour','new_date'],axis=1,inplace=True)
s_59_126.drop(['date','hour','new_date'],axis=1,inplace=True)
s_59_127.drop(['date','hour','new_date'],axis=1,inplace=True)
s_59_128.drop(['date','hour','new_date'],axis=1,inplace=True)

s_60_125.drop(['date','hour','new_date'],axis=1,inplace=True)
s_60_126.drop(['date','hour','new_date'],axis=1,inplace=True)
s_60_127.drop(['date','hour','new_date'],axis=1,inplace=True)
s_60_128.drop(['date','hour','new_date'],axis=1,inplace=True)

s_61_124.drop(['date','hour','new_date'],axis=1,inplace=True)
s_61_125.drop(['date','hour','new_date'],axis=1,inplace=True)
s_61_126.drop(['date','hour','new_date'],axis=1,inplace=True)
s_61_127.drop(['date','hour','new_date'],axis=1,inplace=True)
s_61_128.drop(['date','hour','new_date'],axis=1,inplace=True)
s_61_129.drop(['date','hour','new_date'],axis=1,inplace=True)

s_62_125.drop(['date','hour','new_date'],axis=1,inplace=True)
s_62_126.drop(['date','hour','new_date'],axis=1,inplace=True)
s_62_127.drop(['date','hour','new_date'],axis=1,inplace=True)
s_62_128.drop(['date','hour','new_date'],axis=1,inplace=True)
s_62_129.drop(['date','hour','new_date'],axis=1,inplace=True)

s_63_125.drop(['date','hour','new_date'],axis=1,inplace=True)
s_63_126.drop(['date','hour','new_date'],axis=1,inplace=True)
s_63_127.drop(['date','hour','new_date'],axis=1,inplace=True)

### 하나의 dataframe으로 결합

In [785]:
s_real = pd.concat([s_57_125,
s_57_126,
s_57_127,

s_58_124,
s_58_125,
s_58_126,
s_58_127,

s_59_124,
s_59_125,
s_59_126,
s_59_127,
s_59_128,

s_60_125,
s_60_126,
s_60_127,
s_60_128,

s_61_124,
s_61_125,
s_61_126,
s_61_127,
s_61_128,
s_61_129,

s_62_125,
s_62_126,
s_62_127,
s_62_128,
s_62_129,

s_63_125,
s_63_126,
s_63_127,
],axis=1)

### csv파일 내, 월 구분하는 행이 존재하므로 각 열에서 11개의 NA값 존재 , 해당 NA값 제거

In [786]:
s_real.dropna(inplace=True)

### 비/눈(2) , 눈(3) 에 해당하는 코드값에 비(1) 코드값 부여

In [788]:
for num in s_real.columns:
    s_real[num] = s_real[num].apply(lambda x:1 if x == 2 else x)
for num in s_real.columns:
    s_real[num] = s_real[num].apply(lambda x:1 if x == 3 else x)

In [801]:
s_real.to_csv('D:/INC/Desktop/공모전/KB 국민카드/기상데이터/s_real.csv')